version: '3'

volumes:
  airsift_local_media: {}
  airsift_local_postgres_data: {}
  airsift_local_postgres_data_backups: {}
  airsift_local_traefik: {}

services:
  django:
    restart: always
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    depends_on:
      - postgres
      # - redis
    volumes:
      - airsift_local_media:/app/airsift/media
      - .:/app
    env_file:
      - ./.env
    command: /start
    ports:
      - "0.0.0.0:8000:8000"

  # webpack:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - ./.env
  #   volumes:
  #     - .:/usr/src/app

  postgres:
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    volumes:
      - airsift_local_postgres_data:/var/lib/postgresql/data:Z
      - airsift_local_postgres_data_backups:/backups:z
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  # nginx:
  #   restart: always
  #   image: nginx
  #   volumes:
  #     - airsift_local_media:/usr/share/nginx/html:z
  #   ports:
  #     - "0.0.0.0:3111:80"
  #   env_file:
  #     - ./.env

  # redis:
  #   image: redis:5.0
  #   env_file:
  #     - ./.env

