version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  django:
    restart: always
    image: ghcr.io/commonknowledge/airsift3-app
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    command: /start
    ports:
      - "0.0.0.0:8181:5000"

  postgres:
    restart: always
    image: ghcr.io/commonknowledge/airsift3-postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data:Z
      - production_postgres_data_backups:/backups:z
    env_file:
      - ./.env

  traefik:
    restart: always
    image: ghcr.io/commonknowledge/airsift3-traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  redis:
    image: redis:5.0

