# Generated by Django 3.0.11 on 2020-12-04 14:53

import django.contrib.postgres.fields
from django.db import migrations, models
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20201130_1931'),
        ('datastories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastory',
            options={'verbose_name_plural': 'Data Stories'},
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='body',
        ),
        migrations.AddField(
            model_name='datastory',
            name='acknowledgements_copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write page section'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='actions_copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write page section'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='agriculture',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='agriculture_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='characterofproblem_copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write page section'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='community_observations',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Did your community identify any observations based on your discussions?'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='date_from',
            field=models.DateField(blank=True, null=True, verbose_name='Beginning of report timespan'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='date_to',
            field=models.DateField(blank=True, null=True, verbose_name='End of report timespan'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='dustbox_location_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Roadside', 'Roadside'), ('Garden', 'Garden'), ('Indoors', 'Indoors')], max_length=1000), blank=True, default=list, size=None, verbose_name='What kinds of public green space are in the area?'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='evidenceofproblem_copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write page section'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='evidencesummary_copy',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write page section'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='green_space_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='green_spaces_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Parks', 'Parks'), ('Nature reserve', 'Nature reserve'), ('Woods or Forest', 'Woods or Forest')], max_length=1000), blank=True, default=list, size=None, verbose_name='What kinds of public green space are in the area?'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='impacting_sources_of_pollution_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='How might these sources impact local air-quality and what are the specific sources?'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='industrial_activity',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='industrial_activity_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='introduction_copy',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Write page section'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='landuse_changes_planned_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Residential developments', 'Residential developments'), ('Industrial developments', 'Industrial developments'), ('Development of green space', 'Development of green space'), ('Development of retail sites', 'Development of retail sites')], max_length=1000), blank=True, default=list, size=None, verbose_name='Are there any plans to change the use of the land in the future? (select multiple)'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='landuse_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='landuse_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Retail', 'Retail'), ('Industry', 'Industry'), ('Agriculture', 'Agriculture')], max_length=1000), blank=True, default=list, size=None, verbose_name='Are there any plans to change the use of the land in the future? (select multiple)'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='location_copy',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Write page section'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='location_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='The general location or area this report covers'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='nearby_monitors_data_available_exists',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='nearby_monitors_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='nearby_monitors_exists',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='regional_pollution_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Agricultural', 'Agricultural'), ('Industrial', 'Industrial'), ('Wildfire', 'Wildfire'), ('Volcanic', 'Volcanic')], max_length=1000), blank=True, default=list, size=None, verbose_name='What regional sources of air pollution impact your local area? '),
        ),
        migrations.AddField(
            model_name='datastory',
            name='regional_pollution_sources_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='related_observations',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='observations.Observation', verbose_name='Are there any local observations on Airsift from the monitoring period (and before)'),
        ),
        migrations.AddField(
            model_name='datastory',
            name='waste_disposal',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='waste_disposal_description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
