# Generated by Django 3.0.11 on 2021-02-22 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datastories', '0007_auto_20201218_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastory',
            name='landuse_changes_planned_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Residential developments', 'Residential developments'), ('Industrial developments', 'Industrial developments'), ('Development of green space', 'Development of green space'), ('Development of retail sites', 'Development of retail sites')], max_length=1000), blank=True, default=list, size=None, verbose_name='Are there any plans to change the land use in the future? (select multiple)'),
        ),
        migrations.AlterField(
            model_name='datastory',
            name='landuse_options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('Residential', 'Residential'), ('Retail', 'Retail'), ('Industry', 'Industry'), ('Agriculture', 'Agriculture')], max_length=1000), blank=True, default=list, size=None, verbose_name='How is the land currently being used? (select multiple)'),
        ),
    ]
