# Generated by Django 3.0.11 on 2020-12-10 16:45

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20201208_1657'),
        ('observations', '0002_auto_20201130_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='related_dustboxes',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, to='data.Dustbox', verbose_name='Are there any Airsift Dustboxes monitoring this area?'),
        ),
    ]
