# Generated by Django 3.0.11 on 2020-12-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201217_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, null=True, verbose_name='Canonical URL'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='canonical_url',
            field=models.URLField(blank=True, help_text="Leave blank to use the page's URL.", max_length=255, null=True, verbose_name='Canonical URL'),
        ),
    ]
