# Generated by Django 3.0.11 on 2020-12-03 23:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('device_number', models.CharField(max_length=256)),
                ('entries_number', models.IntegerField()),
                ('last_entry_at', models.DateTimeField(null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('public_key', models.CharField(max_length=256)),
                ('slug', models.SlugField()),
                ('title', models.CharField(max_length=256)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('humidity', models.FloatField()),
                ('pm1', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pm10', models.FloatField()),
                ('temperature', models.FloatField()),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Stream')),
            ],
        ),
    ]
