# Generated by Django 3.0.11 on 2020-12-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='device_number',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
