# Generated by Django 3.0.11 on 2020-12-04 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201204_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
