# Generated by Django 3.0.11 on 2020-12-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20201204_1216'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stream',
            new_name='Dustbox',
        ),
        migrations.RenameModel(
            old_name='Reading',
            new_name='DustboxReading',
        ),
    ]
