# Generated by Django 3.0.11 on 2020-12-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20201207_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dustboxreading',
            old_name='stream',
            new_name='dustbox',
        ),
    ]
