# Generated by Django 3.0.11 on 2020-12-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_dustbox_uuid_to_char'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dustboxreading',
            name='id',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
