# Generated by Django 3.0.11 on 2020-12-18 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20201218_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustboxpage',
            name='related_dustbox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.Dustbox'),
        ),
    ]
