# Generated by Django 3.0.11 on 2020-12-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('data', '0012_dustboxpage_related_dustbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustboxpage',
            name='map_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wagtailimages.Image'),
        ),
    ]
