name: deploy

on:
  push:
    branches: [main]

jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and push (app)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./compose/production/django/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/commonknowledge/airsift3-app:latest
      -
        name: Build and push (postgres)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./compose/production/postgres/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/commonknowledge/airsift3-postgres:latest
      -
        name: Build and push (traefik)
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./compose/production/traefik/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/commonknowledge/airsift3-traefik:latest
      - name: Deploy to staging
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd /var/www/airsift
            docker-compose -f production.yml up -d --build --force-recreate
